### ISSUE TITLE
Slackinvite broken

### ISSUE THREAD

**Issue by pixelbrackets** [php-usergroup-dresden/website#7]
slackinvite.me seems to be down since [March 2017](https://github.com/4xposed/SlackInvite.me/issues/6).

Solution 1: Replace link to »https://slackinvite.me/to/phpugdd« with »https://phpugdd.slack.com/« and state a contact (eg. Twitter handle @phpugdd) which may invite people

Solution 2: Set up a different slack invite service.

**Comment by hollodotme** [comment]
New slack invite app was set up and deployed to heroku. Links on website are fixed.
